import type { HomepageItem, HomepageSection } from "@/lib/types";

export const defaultHomepageSections: HomepageSection[] = [
	{
		id: "works",
		section_key: "works",
		section_name: "Current Works",
		is_visible: true,
		display_order: 1,
	},
	{
		id: "banner",
		section_key: "banner",
		section_name: "Dark Banner",
		is_visible: true,
		display_order: 2,
	},
	{
		id: "clothing",
		section_key: "clothing",
		section_name: "Clothing Section",
		is_visible: true,
		display_order: 3,
	},
	{
		id: "social",
		section_key: "social",
		section_name: "Social Links",
		is_visible: true,
		display_order: 4,
	},
];

export const defaultHomepageItems: HomepageItem[] = [
	{
		id: "work-1",
		item_type: "work",
		title: "BEHOBEN I",
		image_filename: "behoben/behoben_1.webp",
		image_url: null,
		display_order: 1,
		is_visible: true,
	},
	{
		id: "work-2",
		item_type: "work",
		title: "BEHOBEN II",
		image_filename: "behoben/behoben_2.webp",
		image_url: null,
		display_order: 2,
		is_visible: true,
	},
	{
		id: "work-3",
		item_type: "work",
		title: "BEHOBEN III",
		image_filename: "behoben/behoben_3.webp",
		image_url: null,
		display_order: 3,
		is_visible: true,
	},
	{
		id: "work-4",
		item_type: "work",
		title: "BEHOBEN IV",
		image_filename: "behoben/behoben_4.webp",
		image_url: null,
		display_order: 4,
		is_visible: true,
	},
	{
		id: "clothing-1",
		item_type: "clothing",
		title: null,
		image_filename: "clothes1.webp",
		image_url: null,
		display_order: 1,
		is_visible: true,
	},
	{
		id: "clothing-2",
		item_type: "clothing",
		title: null,
		image_filename: "clothes2.webp",
		image_url: null,
		display_order: 2,
		is_visible: true,
	},
	{
		id: "clothing-3",
		item_type: "clothing",
		title: null,
		image_filename: "clothes3.webp",
		image_url: null,
		display_order: 3,
		is_visible: true,
	},
];
